language: python
python:
  - "3.6"     
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch

install:
  - set -e
  - pip install -r requirements.txt

script:
  - set -e
  - pytest

after success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports";

notifications:
  email: false